## **Reduced gradient method**

In [1]:
using Optim, ForwardDiff, LinearAlgebra

The n-variable Rosenbrock test function is

$$
f(x) = \sum_{i=1}^{N-1}[100(x_{i+1} - x_{i}^2)^2+(1-x_i)^2].
$$

Define the 3-variable Rosenbrock test function.

In [2]:
N = 3;
f3(x)= 100.0 * (x[2] - x[1]^2)^2 + (1-x[1])^2 + 100.0 * (x[3]-x[2]^2)^2+(1-x[2])^2

f3 (generic function with 1 method)

Compute its gradient and Hessian using automatic differentiation package.

In [3]:
g(x) = ForwardDiff.gradient(f3, x)
H(x) = ForwardDiff.hessian(f3, x)

H (generic function with 1 method)

Verify that there is a minimizer at $x = (1,1,1)$

In [4]:
x = [1,1,1]
g(x)
cholesky(H(x))
println(eigvals(H(x)))

[0.4751900833635428, 601.667452341669, 1401.8573575749672]


The linear constraint is $x_1+x_2+x3 = 1$ and $2x_1+x_2 = 0.5$.

In [5]:
a1 = ones(1,3) ; b1 = 1
a2 = [2 1 0]; b2 = 0.5
A = vcat(a1,a2); b = vcat(b1,b2);

Compute a basis for Null(A) and verify

In [6]:
Q, R = qr(A'); Z = reshape(Q[:,3],3,1);

Obtain any particular solution

In [7]:
xbar = A \ b

3-element Array{Float64,1}:
 0.08333333333333334
 0.3333333333333333 
 0.5833333333333336 

Define the reduced function and its gradients 

In [8]:
fz(p) = f3(xbar + Z*p)
gz(p) = Z'*g(xbar+Z*p)

gz (generic function with 1 method)

minimize the unconstrained reduced problem.

In [9]:
p0 = [0.]
res = Optim.optimize(fz, gz, p0; inplace = false)

 * Status: success

 * Candidate solution
    Minimizer: [-1.38e-01]
    Minimum:   3.184418e+01

 * Found with
    Algorithm:     L-BFGS
    Initial Point: [0.00e+00]

 * Convergence measures
    |x - x'|               = 1.26e-08 ≰ 0.0e+00
    |x - x'|/|x'|          = 9.10e-08 ≰ 0.0e+00
    |f(x) - f(x')|         = 2.84e-14 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 8.93e-16 ≰ 0.0e+00
    |g(x)|                 = 1.07e-14 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    4
    f(x) calls:    11
    ∇f(x) calls:   11


The minimizer is

In [10]:
p = res.minimizer

1-element Array{Float64,1}:
 -0.1380308998139763

In [11]:
gz(p)

1-element Array{Float64,1}:
 1.0658141036401503e-14

In [12]:
xbar+Z*p

3-element Array{Float64,1}:
 0.026982454453088778
 0.44603509109382244 
 0.526982454453089   

In [27]:
Z' * H(xbar + Z*p)*Z

1×1 Array{Float64,2}:
 283.51047077808664